name: Build Rune OS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Inject ARM64 Kernel Emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
        
      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build debootstrap qemu-user-static
        
      - name: Execute Live Build
        run: sudo lb build
        
      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rune-OS-1.0-Iron-arm64
          path: "*.iso"
          if-no-files-found: error
